implemented GELI, GELI with unenc /boot, GNOP

diff --git a/tools/zfsinstall b/tools/zfsinstall
--- a/tools/zfsinstall
+++ b/tools/zfsinstall
@@ -5,14 +5,20 @@
 # Copyright (c) 2011 Martin Matuska <mm at FreeBSD.org>
 # Modified by @johnko https://github.com/johnko with help from 
 # @keltia https://github.com/keltia
+# encryption setup based on input from 
+# http://forums.freebsd.org/showthread.php?t=2775
 #
-FS_LIST="var tmp"
+RESTOREMASK=`umask`
+FS_NOX="srv/nginx srv/media usr/ports/distfiles var/backups var/db/ports \
+var/db/portsnap var/log var/mail var/spool"
+FS_REG="bootbkp srv srv/tftp-hpa usr usr/local usr/ports var var/db"
+FS_LIST="${FS_REG} ${FS_NOX}"
 
 usage() {
 	echo "Usage: $0 [-h] -d geom_provider [-d geom_provider \
 ...] -t archive_file [-r mirror|raidz] [-m mount_point] [-p zfs_pool_name] \
-[-V zfs_pool_version] [-s swap_partition_size] [-z zfs_partition_size] [-E] \
-[-c] [-l] [-4]"
+[-f zfs_fs_name] [-V zfs_pool_version] [-s swap_partition_size] \
+[-z zfs_partition_size] [-b boot_size] [-E] [-g] [-c] [-l] [-4]"
 }
 
 help() {
@@ -20,40 +26,57 @@ help() {
 	echo; echo "Required flags:"
 	echo "-d geom_provider  : geom provider(s) to install to (e.g. da0)"
 	echo "-t archive_file   : tar archive file containing the FreeBSD distribution"
-	echo "			  supported compression formats are: gzip, bzip2, xz"
+	echo "                    supported compression formats are: gzip, bzip2, xz"
 	echo; echo "Optional flags:"
 	echo "-r raidz|mirror   : select raid mode if more than one -d provider given"
 	echo "-s swap_part_size : create a swap partition with given size (default: no swap)"
 	echo "-z zfs_part_size  : create zfs parition of this size (default: all space left)"
 	echo "-p pool_name      : specify a name for the ZFS pool (default: tank)"
+	echo "-f fs_name        : specify a name for the ZFS filesystem (default: rfs)"
 	echo "-V pool_version   : specify a version number for ZFS pool (default: 13)"
 	echo "-m mount_point    : use this mount point for operations (default: /mnt)"
-	echo "-E		: enable GELI support incl. encrypted/mirrored swap"
-	echo "-c		: enable lzjb compression for all datasets"
-	echo "-l 		: use legacy mounts (via fstab) instead of ZFS mounts"
-	echo "-4		: use fletcher4 as default checksum algorithm"
+	echo "-b boot_size      : create a unencrypted boot partition (default: 200M)"
+	echo "-E  : enable GELI support incl. encrypted/mirrored swap"
+	echo "-g  : enable NOP support to emulate 4k alignment"
+	echo "-c  : enable lzjb compression for all datasets"
+	echo "-l  : use legacy mounts (via fstab) instead of ZFS mounts"
+	echo "-4  : use fletcher4 as default checksum algorithm"
 	echo; echo "Examples:"
 	echo "Install on a single drive with 2GB swap:"
 	echo "$0 -d ad4 -s 2G"
 	echo "Install on a mirror without swap, pool name rpool:"
 	echo "$0 -d ad4 -d ad6 -r mirror -p rpool"
+	echo "Install GELI encrypted / with unencrypted /boot using \
+  key and password at boot time:"
+	echo "$0 -d ad4 -b 200M -E"
+	echo "Install GELI encrypted / that can't boot (maybe useful if using \
+  custom mfsbsd to boot, unlock, chroot, and continue rc):"
+	echo "$0 -d ad4 -E"
+	echo; echo "Note about ENCRYPTION:"
+  echo "You must backup your keyfiles and headers to a safe (and secure) location."
+  echo "Without them, you will not be able to unlock or restore your data"
+  echo "from corrupt disk headers."
+  echo "You need to remember the password you used if you installed using the -b option."
 	echo; echo "Notes:"
 	echo "When using swap and raidz/mirror, the swap partition is created on all drives."
 	echo "The /etc/fstab entry will contatin only the first drive's swap partition."
 	echo "You can enable all swap partitions and/or make a gmirror-ed swap later."
 }
 
-while getopts d:t:r:p:s:z:m:V:hcEl4 o; do
+while getopts d:t:r:p:f:s:z:m:b:V:hcgEl4 o; do
 	case "$o" in
         	d) DEVS="$DEVS ${OPTARG##/dev/}" ;;
         	t) ARCHIVE="${OPTARG}" ;;
         	p) POOL="${OPTARG}" ;;
+        	f) RFS="${OPTARG}" ;;
         	s) SWAP="${OPTARG}" ;;
         	m) MNT="${OPTARG}" ;;
+        	b) BSIZE="${OPTARG}"; USEBOOT=1;;
 		r) RAID="${OPTARG}" ;;
 		z) ZPART="${OPTARG}" ;;
 		V) VERSION="${OPTARG}" ;;
-		E) GELI=1 ;;
+		E) GELI=1; LEGACY=1 ;;
+		g) GNOP=1 ;;
 		c) LZJB=1 ;;
 		l) LEGACY=1 ;;
 		4) FLETCHER=1 ;;
@@ -83,6 +106,18 @@ fi
 
 if [ -z "$POOL" ]; then
 	POOL=tank
+fi
+
+if [ -z "$RFS" ]; then
+	RFS=rfs
+fi
+
+if [ -z "$BSIZE" ]; then
+	if [ "${USEBOOT}" = "1" ]; then
+		BSIZE=200M
+	else
+		BSIZE=1M
+	fi
 fi
 
 if [ -z "$VERSION" ]; then
@@ -193,6 +228,9 @@ fi
 # Create GPT
 
 for DEV in ${DEVS}; do
+	echo -n "zpool labelclear ${DEV} ..."
+	/sbin/zpool labelclear -f /dev/${DEV} > /dev/null 2>&1
+	echo " done"
 	echo -n "Creating GUID partitions on ${DEV} ..."
 	if ! /sbin/gpart create -s GPT /dev/${DEV} > /dev/null; then
 		echo " error"
@@ -207,12 +245,18 @@ for DEV in ${DEVS}; do
 		echo " error"
 		exit 1
 	fi
+	if [ -n "${BSIZE}" ]; then
+		if ! /sbin/gpart add -t freebsd-ufs -a 4k -s ${BSIZE} ${DEV} > /dev/null ; then
+			echo " error"
+			exit 1
+		fi
+	fi
 	if [ -n "${SWAP}" ]; then
 		if ! /sbin/gpart add -t freebsd-swap -a 4k -s "${SWAP}" ${DEV} > /dev/null; then
 			echo " error"
 			exit 1
 		fi
-		SWAPPART=`/sbin/glabel status ${DEV}p2 | /usr/bin/grep gptid | /usr/bin/awk '{ print $1 }'`
+		SWAPPART=`/sbin/glabel status ${DEV}p3 | /usr/bin/grep gptid | /usr/bin/awk '{ print $1 }'`
 		if [ -z "$SWAPPART" ]; then
 			echo " error determining swap partition"
 		fi
@@ -229,15 +273,26 @@ for DEV in ${DEVS}; do
 		exit 1
 	fi
 	/bin/dd if=/dev/zero of=/dev/${DEV}p2 bs=512 count=560 > /dev/null 2> /dev/null
+	/sbin/zpool labelclear -f /dev/${DEV}p2 > /dev/null 2>&1
+	/bin/dd if=/dev/zero of=/dev/${DEV}p3 bs=512 count=560 > /dev/null 2> /dev/null
+	/sbin/zpool labelclear -f /dev/${DEV}p3 > /dev/null 2>&1
 	if [ -n "${SWAP}" ]; then
-		/bin/dd if=/dev/zero of=/dev/${DEV}p3 bs=512 count=560 > /dev/null 2> /dev/null
+		/bin/dd if=/dev/zero of=/dev/${DEV}p4 bs=512 count=560 > /dev/null 2> /dev/null
+		/sbin/zpool labelclear -f /dev/${DEV}p4 > /dev/null 2>&1
 	fi
 	echo " done"
 
 	echo -n "Configuring ZFS bootcode on ${DEV} ..."
+	if [ "${USEBOOT}" = "1" ]; then
+		if ! /sbin/gpart bootcode -b /boot/pmbr -p /boot/gptboot -i 1 ${DEV} > /dev/null; then
+			echo " error"
+			exit 1
+		fi
+	else
 		if ! /sbin/gpart bootcode -b /boot/pmbr -p /boot/gptzfsboot -i 1 ${DEV} > /dev/null; then
-		echo " error"
-		exit 1
+			echo " error"
+			exit 1
+		fi
 	fi
 	echo " done"
 	/sbin/gpart show ${DEV}
@@ -250,22 +305,75 @@ fi
 
 # Create zpool and zfs
 
+KEYFILES=""
 for DEV in ${DEVS}; do
-	PART=`/sbin/gpart show ${DEV} | /usr/bin/grep freebsd-zfs | /usr/bin/awk '{ print $3 }'`
+	PART=`/sbin/gpart show ${DEV} | /usr/bin/grep freebsd-zfs | /usr/bin/head -1 \
+| /usr/bin/awk '{ print $3 }'`
+	DISKLABEL=`/sbin/glabel list ${DEV}p${PART} | /usr/bin/grep gptid \
+| /usr/bin/awk -F"gptid/" '{ print $2 }'`
 
 	if [ -z "${PART}" ]; then
 		echo Error: freebsd-zfs partition not found on /dev/$DEV
 		exit 1
 	fi
+	if [ "${GELI}" = "1" ]; then
+		/bin/mkdir -p /boot/keys > /dev/null 2>&1
+		##### Generate an alphanumeric key
+		umask 077
+		TMPKEY="/boot/keys/`hostname -s`.${POOL}.${DISKLABEL}.${PART}"
+		/bin/cat /dev/urandom | /usr/bin/strings -1 | /usr/bin/egrep -o "[[:alnum:]]" \
+| /usr/bin/tr -d '\n' | /usr/bin/head -c64 > ${TMPKEY}
+		umask $RESTOREMASK
+		KEYFILES="${KEYFILES} ${TMPKEY}"
+	fi
 
-	GPART=`/sbin/glabel list ${DEV}p${PART} | /usr/bin/grep gptid | /usr/bin/awk -F"gptid/" '{ print "gptid/" $2 }'`
+	BOOTPART=`/sbin/gpart show ${DEV} | /usr/bin/grep freebsd-ufs | /usr/bin/head -1 \
+| /usr/bin/awk '{ print $3 }'`
+	BPART="${DEV}p${BOOTPART}"
+	BPARTS="${BPARTS} ${BPART}"
 
-	GPARTS="${GPARTS} ${GPART}"
+	if [ "${GNOP}" = "1" ]; then
+		GPART=`/sbin/glabel list ${DEV}p${PART} | /usr/bin/grep gptid \
+| /usr/bin/awk -F"gptid/" '{ print "gptid/" $2 }'`
+		/sbin/gnop create -S 4096 ${GPART}
+		GPARTS="${GPARTS} ${GPART}.nop"
+	fi
+	if [ "${GELI}" = "1" ]; then
+		if [ "${USEBOOT}" = "1" ]; then
+			##### PASSWORD AT CONSOLE
+			/sbin/geli init -b    -K ${TMPKEY} -e AES-XTS -s 4096 /dev/${DEV}p${PART}
+			/sbin/geli attach     -k ${TMPKEY} /dev/${DEV}p${PART}
+		else
+			##### PASSWORDLESS
+			/sbin/geli init -b -P -K ${TMPKEY} -e AES-XTS -s 4096 /dev/${DEV}p${PART}
+			/sbin/geli attach  -p -k ${TMPKEY} /dev/${DEV}p${PART}
+		fi
+		EPARTS="${EPARTS}${DEV}p${PART}.eli "
+	fi
 	PARTS="${PARTS} ${DEV}p${PART}"
+	umask 077
+	/bin/cat >> /boot/loader.keys <<EOF
+geli_${DEV}p${PART}_keyfile0_load="YES"
+geli_${DEV}p${PART}_keyfile0_type="${DEV}p${PART}:geli_keyfile0"
+geli_${DEV}p${PART}_keyfile0_name="${TMPKEY}"
+EOF
+	umask $RESTOREMASK
 done
 
-echo -n "Creating ZFS pool ${POOL} on${PARTS} ..."
-if ! /sbin/zpool create -f -m none ${ALTROOT} ${VERSION} ${POOL} ${RAID} ${PARTS} > /dev/null 2> /dev/null; then
+if [ "${USEBOOT}" = 1 ]; then
+	/sbin/gmirror label -b load boot ${BPARTS}
+fi
+
+POOLPARTS=${PARTS}
+if [ "${GNOP}" = "1" ]; then
+	POOLPARTS=${GPARTS}
+fi
+if [ "${GELI}" = "1" ]; then
+	POOLPARTS=${EPARTS}
+fi
+
+echo -n "Creating ZFS pool ${POOL} on ${POOLPARTS} ..."
+if ! /sbin/zpool create -f -m none ${ALTROOT} ${VERSION} ${POOL} ${RAID} ${POOLPARTS} > /dev/null 2> /dev/null; then
 	echo " error"
 	exit 1
 fi
@@ -289,28 +397,28 @@ if [ "${LZJB}" = "1" ]; then
 	echo " done"
 fi
 
-echo -n "Creating ${POOL} root partition:"
-if ! /sbin/zfs create -o mountpoint=${ROOTMNT} ${POOL}/root > /dev/null 2> /dev/null; then
+echo -n "Creating ${POOL} ${RFS} partition:"
+if ! /sbin/zfs create -o mountpoint=${ROOTMNT} ${POOL}/${RFS} > /dev/null 2> /dev/null; then
 	echo " error"
 	exit 1
 fi
 echo " ... done"
 echo -n "Creating ${POOL} partitions:"
 for FS in ${FS_LIST}; do
-	if [ "${LEGACY}" = 1 ]; then
+	if [ "${LEGACY}" = "1" ]; then
 		MNTPT="-o mountpoint=legacy"
 	else
 		MNTPT=
 	fi
-	if ! /sbin/zfs create ${MNTPT} ${POOL}/root/${FS} > /dev/null 2> /dev/null; then
+	if ! /sbin/zfs create ${MNTPT} ${POOL}/${RFS}/${FS} > /dev/null 2> /dev/null; then
 		echo " error"
 		exit 1
 	fi
 	echo -n " ${FS}"
 done
 echo " ... done"
-echo -n "Setting bootfs for ${POOL} to ${POOL}/root ..."
-if ! /sbin/zpool set bootfs=${POOL}/root ${POOL} > /dev/null 2> /dev/null; then
+echo -n "Setting bootfs for ${POOL} to ${POOL}/${RFS} ..."
+if ! /sbin/zpool set bootfs=${POOL}/${RFS} ${POOL} > /dev/null 2> /dev/null; then
 	echo " error"
 	exit 1
 fi
@@ -321,18 +429,29 @@ echo " done"
 if [ "${LEGACY}" = "1" ]; then
 	echo -n "Mounting ${POOL} on ${MNT} ..."
 	/bin/mkdir -p ${MNT}
-	if ! /sbin/mount -t zfs ${POOL}/root ${MNT} > /dev/null 2> /dev/null; then
-		echo " error mounting pool/root"
+	if ! /sbin/mount -t zfs ${POOL}/${RFS} ${MNT} > /dev/null 2> /dev/null; then
+		echo " error mounting ${POOL}/${RFS}"
 		exit 1
 	fi
 	for FS in ${FS_LIST}; do
 		/bin/mkdir -p ${MNT}/${FS}
-		if ! /sbin/mount -t zfs ${POOL}/root/${FS} ${MNT}/${FS} > /dev/null 2> /dev/null; then
-			echo " error mounting ${POOL}/root/${FS}"
+		if ! /sbin/mount -t zfs ${POOL}/${RFS}/${FS} ${MNT}/${FS} > /dev/null 2> /dev/null; then
+			echo " error mounting ${POOL}/${RFS}/${FS}"
 			exit 1
 		fi
 	done
-echo " done"
+	echo " done"
+fi
+
+if [ "${USEBOOT}" = "1" ]; then
+	##### Create /bootdir
+	echo -n "Creating /bootdir on /dev/mirror/boot ..."
+	newfs -n /dev/mirror/boot > /dev/null 2>&1 || exit 1
+	if [ ! -e ${MNT}/bootdir ]; then
+		mkdir ${MNT}/bootdir
+	fi
+	mount /dev/mirror/boot ${MNT}/bootdir || exit 1
+	echo " done"
 fi
 
 echo -n "Extracting FreeBSD distribution ..."
@@ -352,14 +471,41 @@ echo " done"
 # Adjust configuration files
 
 echo -n "Writing /boot/loader.conf..."
-echo "zfs_load=\"YES\"" > ${MNT}/boot/loader.conf
+/bin/cat >>${MNT}/boot/loader.conf <<EOF
+zfs_load="YES"
+aesni_load="YES"
+ahci_load="YES"
+EOF
 if [ "${GELI}" = "1" ]; then
-	echo "geom_mirror_load=\"YES\"" > ${MNT}/boot/loader.conf
-	echo "geom_label_load=\"YES\"" > ${MNT}/boot/loader.conf
-	echo "geom_eli_load=\"YES\"" > ${MNT}/boot/loader.conf
-#	echo "geom_uzip_load=\"YES\"" > ${MNT}/boot/loader.conf
+	/bin/cat >>${MNT}/boot/loader.conf <<EOF
+geom_mirror_load="YES"
+geom_label_load="YES"
+geom_eli_load="YES"
+geom_uzip_load="YES"
+EOF
+	umask 077
+	/bin/mkdir -p ${MNT}/var/backups > /dev/null 2>&1
+	/bin/cp -Rpv /var/backups/*.eli ${MNT}/var/backups/
+	umask $RESTOREMASK
+	/bin/cat >>${MNT}/etc/rc.conf <<EOF
+geli_swap_flags="-e AES-XTS -l 256 -s 4096 -d"
+EOF
 fi
-echo "vfs.root.mountfrom=\"zfs:${POOL}/root\"" >> ${MNT}/boot/loader.conf
+if [ "${USEBOOT}" = "1" ]; then
+	/bin/cat >>${MNT}/boot/loader.conf <<EOF
+vfs.root.mountfrom="ufs:/dev/mirror/boot"
+EOF
+	umask 077
+	/bin/mkdir -p ${MNT}/boot/keys > /dev/null 2>&1
+	for k in ${KEYFILES}; do
+		/bin/cp -pv ${k} ${MNT}/boot/keys/
+	done
+	umask $RESTOREMASK
+	/bin/cat /boot/loader.keys >> ${MNT}/boot/loader.conf
+fi
+/bin/cat >>${MNT}/boot/loader.conf <<EOF
+vfs.root.mountfrom="zfs:${POOL}/${RFS}"
+EOF
 echo " done"
 
 # Write fstab if swap or legacy
@@ -377,10 +523,16 @@ if [ -n "${FSWAP}" -o "${LEGACY}" = "1" ]; then
 		fi
 	fi
 	if [ "${LEGACY}" = "1" ]; then
-		for FS in ${FS_LIST}; do
-			echo ${POOL}/root/${FS} /${FS} zfs rw 0 0 >> ${MNT}/etc/fstab
+		for FS in ${FS_REG}; do
+			echo ${POOL}/${RFS}/${FS} /${FS} zfs rw 0 0 >> ${MNT}/etc/fstab
+		done
+		for FS in ${FS_NOX}; do
+			echo ${POOL}/${RFS}/${FS} /${FS} zfs rw,nosuid,noexec,nodev 0 0 >> ${MNT}/etc/fstab
 		done
 	fi
+fi
+if [ "${USEBOOT}" = "1" ]; then
+	echo /dev/mirror/boot /bootdir ufs rw,noatime 0 0 >> ${MNT}/etc/fstab
 fi
 if [ "${LEGACY}" != "1" ]; then
 	echo -n "Writing /etc/rc.conf..."
@@ -395,6 +547,10 @@ if [ -n "${LEGACY}" ]; then
 	done
 	/sbin/umount ${MNT} > /dev/null 2> /dev/null
 fi
+if ! umount ${MNT}/bootdir > /dev/null 2>&1 ; then
+  echo " error unmounting /bootdir"
+  exit 1
+fi
 if ! /sbin/zpool export ${POOL} > /dev/null 2> /dev/null; then
 	echo " error exporting pool"
 	exit 1
@@ -404,10 +560,14 @@ if ! /sbin/zpool import ${ALTROOT} ${POOL} > /dev/null 2> /dev/null; then
 	exit 1
 fi
 if [ -n "${LEGACY}" ]; then
-	if ! /sbin/mount -t zfs ${POOL}/root ${MNT} > /dev/null 2> /dev/null; then
-		echo " error mounting ${POOL}/root"
+	if ! /sbin/mount -t zfs ${POOL}/${RFS} ${MNT} > /dev/null 2> /dev/null; then
+		echo " error mounting ${POOL}/${RFS}"
 		exit 1
 	fi
+fi
+if ! mount /dev/mirror/boot ${MNT}/bootdir > /dev/null 2>&1 ; then
+  echo " error remounting /bootdir"
+  exit 1
 fi
 if ! /bin/cp /boot/zfs/zpool.cache ${MNT}/boot/zfs/ > /dev/null 2> /dev/null; then
 	echo " error copying zpool.cache"
@@ -415,13 +575,22 @@ if ! /bin/cp /boot/zfs/zpool.cache ${MNT}/boot/zfs/ > /dev/null 2> /dev/null; th
 fi
 if [ -n "${LEGACY}" ]; then
 	for FS in ${FS_LIST}; do
-		if ! /sbin/mount -t zfs ${POOL}/${FS} ${MNT}/${FS} > /dev/null 2> /dev/null; then
-		echo " error mounting ${POOL}/${FS}"
+		if ! /sbin/mount -t zfs ${POOL}/${RFS}/${FS} ${MNT}/${FS} > /dev/null 2> /dev/null; then
+		echo " error mounting ${POOL}/${RFS}/${FS}"
 		exit 1
 		fi
 	done
 fi
 echo " done"
+
+if [ "$USEBOOT" = "1" ]; then
+	echo -n "Linking /bootdir ..."
+	cd ${MNT}
+	/bin/mv boot bootdir/ || exit 1
+	/bin/ln -s bootdir/boot ${MNT}/boot || exit 1
+	/bin/chflags -h sunlink ${MNT}/boot || exit 1
+	echo " done"
+fi
 
 # Mount devfs for post-configuration
 
@@ -438,3 +607,10 @@ echo "For example, change the root password or edit/create /etc/rc.conf for"
 echo "for system services. "
 echo ""
 echo "WARNING - Don't export ZFS pool \"${POOL}\"!"
+if [ "${GELI}" = "1" ]; then
+echo "!!!!!!!!!!"
+echo "! YOU MUST BACKUP YOUR KEYS FROM /boot/keys/"
+echo "! YOU MUST BACKUP YOUR HEADERS FROM /var/backups/"
+echo "!!!!!!!!!!"
+fi
+
